version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    env_file:
      - config.env
    volumes:
      - ./data:/data/db
    restart: unless-stopped
