version: '3.7'
services:
  mongodb_container:
    image: mongo:4.4-rc
    ports:
      - "127.0.0.1:27017:27017"
    env_file:
      - config.env
    volumes:
      - ./data:/data/db
    restart: unless-stopped
